version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi
    environment:
      SWAGGER_JSON: /openapi
